name: wega_vin_timer
description: Aplikacja Flutter do obsługi lokalizacji i czynności pojazdów WEGA.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.2.10
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  mobile_scanner: ^6.0.2
  google_mlkit_text_recognition: ^0.13.1
  flutter_local_notifications: ^17.2.4
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
